<?php


namespace app\admin\controller;


use app\common\BaseController;
use app\admin\model\Administrator;

class Base extends BaseController
{
    protected $self;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $uid = $this->user_info['uid'];
        $this->self = Administrator::get($uid);
    }
}