<?php


namespace app\web\controller;


use app\common\BaseController;
use app\common\error\ErrorCode;
use app\common\exception\ApiException;
use app\common\model\User as UserModel;

class Base extends BaseController
{
    protected $user;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->user = UserModel::get($this->user_info['uid']);
        if ($this->user->status != UserModel::STATUS_NORMAL) {
            throw new ApiException(ErrorCode::USER_LOCKED);
        }
    }
}