<?php


namespace app\web\controller;


use app\common\error\ErrorCode;
use app\common\exception\ApiException;
use app\common\model\Pickman as PickmanModel;
use app\common\model\Depot as DepotModel;
use think\Controller;
use think\Exception\DbException;

class Depot extends Base
{
    protected $depot;

    /**
     * 初始化
     * @throws ApiException
     * @throws DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $openid = $this->user_info['openid'];
        $this->depot = DepotModel::with(['area'])->get(['openid' => $openid]);
        if (!$this->depot) {
            throw new ApiException(ErrorCode::DEPOT_NOT_LOGIN);
        }
    }

    /**
     * 获取回收点信息
     * return mixed
     */
    public function info()
    {
        $depot = $this->depot;
        unset($depot['id']);
        unset($depot['openid']);
        unset($depot['password']);

        return success($depot);
    }

}