<?php


namespace app\web\controller;


use app\common\error\ErrorCode;
use app\common\exception\ApiException;
use app\common\model\OrderMaster as OrderMasterModel;
use app\common\model\Pickman as PickmanModel;
use app\common\model\User as UserModel;
use \Requests;
use think\Exception\DbException;
use think\facade\Cache;

class Pickman extends Base
{
    protected $pickman;

    /**
     * 初始化
     * @throws ApiException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $openid = $this->user_info['openid'];
        $this->pickman = PickmanModel::get(['openid' => $openid]);
        if (!$this->pickman) {
            throw new ApiException(ErrorCode::PICKMAN_NOT_EXISTS);
        }
        if ($this->pickman->status == PickmanModel::STATUS_WAIT) {
            $this->pickman;
//            throw new ApiException(ErrorCode::PICKMAN_WAIT_AUDIT);
        } elseif ($this->pickman->status == PickmanModel::STATUS_FORBIDDEN) {
            throw new ApiException(ErrorCode::PICKMAN_FORBIDDEN);
        }
    }

    /**
     * 获取回收员信息
     * return mixed
     */
    public function info()
    {
        $pickman = $this->pickman;
        unset($pickman['id']);
        unset($pickman['openid']);
        unset($pickman['password']);

        return success($pickman);
    }

    /**
     * 导航到目的地
     */
    public function navigate()
    {
        $param = $this->request->get();
        // 取出订单信息
        $order = OrderMasterModel::get($param['id']);
        $detail = $order->area.$order->address_detail;
        // 获得目的地坐标
        $target_info = $this->address2location($detail);
        $target_location = $target_info['location']['lat'].','.$target_info['location']['lng'];
        if (isset($param['self_pos']) && !empty($param['self_pos'])) {
            $self_location = $param['self_pos'];
        } else {
            $user = UserModel::get($this->user_info['uid']);
            $openid = $user->openid;
            $self_location = Cache::get("$openid.location");
            if (!$self_location) {
                $self_location = '37.520755,121.357534';
            }
        }
        $key = config('secret.qqMap.key');
        $way_list = ['driving', 'bicycling', 'transit', 'walking'];
        $way = 'driving';
        $api = "https://apis.map.qq.com/ws/direction/v1/$way/?from=$self_location&to=$target_location&key=$key";
        $response = Requests::get($api);
        $data = json_decode($response->body, true);
        return success($data);
    }

    private function address2location($address)
    {
        $key = config('secret.qqMap.key');
        $api = "https://apis.map.qq.com/ws/geocoder/v1/?address=$address&key=$key";
        $response = Requests::get($api);
        $data = json_decode($response->body, true);
        return $data['result'];
    }
}