<?php


namespace app\web\controller;


use app\common\error\ErrorCode;
use app\common\exception\ApiException;
use app\common\model\Pickman as PickmanModel;

class Pickman extends Base
{
    protected $pickman;

    /**
     * 初始化
     * @throws ApiException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $openid = $this->user_info['openid'];
        $this->pickman = PickmanModel::get(['openid' => $openid]);
        if (!$this->pickman) {
            throw new ApiException(ErrorCode::PICKMAN_NOT_EXISTS);
        }
        if ($this->pickman->status == PickmanModel::STATUS_WAIT) {
            throw new ApiException(ErrorCode::PICKMAN_WAIT_AUDIT);
        } elseif ($this->pickman->status == PickmanModel::STATUS_FORBIDDEN) {
            throw new ApiException(ErrorCode::PICKMAN_FORBIDDEN);
        }
    }

    /**
     * 获取回收员信息
     * return mixed
     */
    public function info()
    {
        $pickman = $this->pickman;
        unset($pickman['id']);
        unset($pickman['openid']);
        unset($pickman['password']);

        return success($pickman);
    }
}