<?php


namespace app\web\controller;


use app\common\error\ErrorCode;
use app\common\exception\ApiException;
use app\common\model\Pickman as PickmanModel;
use \Requests;

class Pickman extends Base
{
    protected $pickman;

    /**
     * 初始化
     * @throws ApiException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $openid = $this->user_info['openid'];
        $this->pickman = PickmanModel::get(['openid' => $openid]);
        if (!$this->pickman) {
            throw new ApiException(ErrorCode::PICKMAN_NOT_EXISTS);
        }
        if ($this->pickman->status == PickmanModel::STATUS_WAIT) {
            $this->pickman;
//            throw new ApiException(ErrorCode::PICKMAN_WAIT_AUDIT);
        } elseif ($this->pickman->status == PickmanModel::STATUS_FORBIDDEN) {
            throw new ApiException(ErrorCode::PICKMAN_FORBIDDEN);
        }
    }

    /**
     * 获取回收员信息
     * return mixed
     */
    public function info()
    {
        $pickman = $this->pickman;
        unset($pickman['id']);
        unset($pickman['openid']);
        unset($pickman['password']);

        return success($pickman);
    }

    /**
     * 导航到目的地
     */
    public function navigation()
    {
        $self_location = '37.520755,121.357534';
        $key = config('secret.qqMap.key');
        $target_location = '';
        $way_list = ['driving', 'bicycling', 'transit', 'walking'];
        $way = 'driving';
        $api = "https://apis.map.qq.com/ws/direction/v1/$way/?from=$self_location&to=$target_location&key=$key";
        $response = Requests::get($api);
        dump($response->body);
    }
}