<?php
namespace app\index\controller;

use app\common\error\ErrorCode;
use app\common\exception\ApiException;
use app\common\model\User;
use Firebase\JWT\JWT;
use think\facade\Cache;
use think\Controller;
use think\exception\ValidateException;
use think\facade\Request;
use think\facade\Validate;
use \Requests;

class Wx extends Controller
{
    private $access_token;
    private $app_id;
    private $app_secret;

    /**
     * 初始化 验证access_token有效期
     * @throws ApiException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $access_token = Cache::get('wx_access_token');
        $this->app_id = config('secret.wx.appId');
        $this->app_secret = config('secret.wx.appSecret');
        if (!$access_token) {
            // 没有access_token
            $this->access_token = $this->getAccessToken();
        } else {
            $access_token_expire_time = Cache::get('wx_access_token_expire_time');
            if (time() > $access_token_expire_time) {
                // access_token过期
                $this->access_token = $this->getAccessToken();
            } else {
                // 没过期
                $this->access_token = $access_token;
            }
        }
    }

    /**
     * 获取access_token写入到缓存
     * @throws ApiException
     * @return mixed
     */
    private function getAccessToken()
    {
        $app_id = $this->app_id;
        $app_secret = $this->app_secret;
        $api = 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid='.$app_id.'&secret='.$app_secret;
        $response = Requests::get($api);
        $data = json_decode($response->body, true);
        if (array_key_exists('errcode', $data)) {
            throw new ApiException(ErrorCode::WX_AUTH_ERROR, 500, '获取access_token失败:'.$data['errmsg']);
        }
        Cache::set('wx_access_token', $data['access_token']);
        Cache::set('wx_access_token_expire_time', time()+$data['expires_in']);
        return $data['access_token'];
    }

    /**
     * 获取api票据
     * @return mixed
     * @throws ApiException
     */
    private function getJsApiTicket()
    {
        $access_token = $this->access_token;
        $response = Requests::get('https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token='.$access_token.'&type=jsapi');
        $data = json_decode($response->body, true);
        if ($data['errcode'] != 0) {
            throw new ApiException(ErrorCode::WX_AUTH_ERROR, 500, '获取api票据失败:'.$data['errmsg']);
        }
        Cache::set('wx_ticket', $data['ticket']);
        Cache::set('wx_ticket_expire_time', time()+$data['expires_in']);
        return $data['ticket'];
    }

    /**
     * 生成随机字符串
     * @param int $length
     * @return string
     */
    private function createNonceStr($length = 16) {
        $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        $str = "";
        for ($i = 0; $i < $length; $i++) {
            $str .= substr($chars, mt_rand(0, strlen($chars) - 1), 1);
        }
        return $str;
    }

    /**
     * 生成网页js-sdk配置
     * @return mixed
     * @throws ApiException
     */
    public function sdkConf()
    {
        $url = $this->request->get('url');

        if (!$url) {
            throw new ValidateException('请填写调用sdk的地址');
        }
        $ticket = Cache::get('wx_ticket');
        if (!$ticket) {
            // 没有ticket
            $ticket = $this->getJsApiTicket();
        } else {
            $ticket_expire_time = Cache::get('wx_ticket_expire_time');
            if (time() > $ticket_expire_time) {
                // ticket过期
                $ticket = $this->getJsApiTicket();
            }
        }
        $nonceStr = $this->createNonceStr();
        $timestamp = time();
        $string = "jsapi_ticket=$ticket&noncestr=$nonceStr&timestamp=$timestamp&url=$url";
//        echo $string;
        $signature = sha1($string);
        return success([
            'appId' => $this->app_id,
            'nonceStr' => $nonceStr,
            'timestamp' => $timestamp,
            'signature' => $signature,
            'rawString' => $string,
            'url' => $url
        ]);
    }

    /**
     * 模板消息
     * @param $openid
     * @param $template_id
     * @param $url
     * @param array $data
     * @return array
     */
    public function sendMessage($openid, $template_id, $url, $data = [])
    {
        $data = [
            "touser" => $openid,
            "template_id" => $template_id,
            "url" => $url,
            "topcolor" => "#FF0000",
            "data" => $data,
//            "data" => [
//                "User" => [
//                    "value" => "黄先生",
//                    "color" => "#173177"
//                ]
//            ]
        ];
        $access_token = $this->access_token;
        $api = "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=$access_token";
        $headers = ['Content-Type' => 'application/json'];
        $response = Requests::post($api, $headers, json_encode($data));
        return json_decode($response->body, true);
    }
}
